name: delivery_tracker
description: A package useful to retrieve information about your deliveries using the tracking number.
version: 1.0.0-Alpha
homepage: https://github.com/trobugno/delivery_tracker

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.1
  intl: ^0.17.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: